import { IPublicAuthorityNode, ICitizenRTIDossier } from '../types/dossier.js';
import { TimelineEvent } from '../types/timeline.js';

export const INITIAL_PUBLIC_AUTHORITIES: IPublicAuthorityNode[] = [
  {
    id: 'pa-nhai-001',
    ministryId: 'min-morth',
    ministryName: 'Ministry of Road Transport and Highways',
    canonicalName: 'National Highways Authority of India (NHAI)',
    hindiName: 'भारतीय राष्ट्रीय राजमार्ग प्राधिकरण',
    portalType: 'CENTRAL_ONLINE',
    portalId: 'NHAI',
    dropdownPath: ['Ministry of Road Transport and Highways', 'National Highways Authority of India'],
    cpioDesignation: 'Chief General Manager (Tech-II) & CPIO',
    officeAddress: 'G 5&6, Sector-10, Dwarka, New Delhi - 110075',
    pincode: '110075',
    stateLgdCode: 7, // Delhi
    districtLgdCode: 90,
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'Member (Administration) & First Appellate Authority',
    complianceRating: 88,
    medianResponseDays: 24,
  },
  {
    id: 'pa-epfo-002',
    ministryId: 'min-labour',
    ministryName: 'Ministry of Labour and Employment',
    canonicalName: "Employees' Provident Fund Organisation (EPFO)",
    hindiName: 'कर्मचारी भविष्य निधि संगठन',
    portalType: 'CENTRAL_ONLINE',
    portalId: 'EPFO',
    dropdownPath: ['Ministry of Labour and Employment', "Employees' Provident Fund Organisation"],
    cpioDesignation: 'Regional P.F. Commissioner-I (Pension/RTI)',
    officeAddress: 'Bhavishya Nidhi Bhawan, 14, Bhikaiji Cama Place, New Delhi - 110066',
    pincode: '110066',
    stateLgdCode: 7,
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'Additional Central P.F. Commissioner (HQ)',
    complianceRating: 72,
    medianResponseDays: 28,
  },
  {
    id: 'pa-food-003',
    ministryId: 'min-food',
    ministryName: 'Ministry of Consumer Affairs, Food and Public Distribution',
    canonicalName: 'Department of Food and Public Distribution (NFSA)',
    hindiName: 'खाद्य और सार्वजनिक वितरण विभाग',
    portalType: 'CENTRAL_ONLINE',
    portalId: 'DFPDS',
    dropdownPath: ['Ministry of Consumer Affairs, Food and Public Distribution', 'Department of Food and Public Distribution'],
    cpioDesignation: 'Deputy Secretary (Policy-III) & CPIO',
    officeAddress: 'Krishi Bhawan, Dr. Rajendra Prasad Road, New Delhi - 110001',
    pincode: '110001',
    stateLgdCode: 7,
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'Joint Secretary (Impex & Storage) & FAA',
    complianceRating: 81,
    medianResponseDays: 26,
  },
  {
    id: 'pa-iocl-004',
    ministryId: 'min-petroleum',
    ministryName: 'Ministry of Petroleum and Natural Gas',
    canonicalName: 'Indian Oil Corporation Limited (IOCL)',
    hindiName: 'इंडियन ऑयल कॉर्पोरेशन लिमिटेड',
    portalType: 'CENTRAL_ONLINE',
    portalId: 'IOCL',
    dropdownPath: ['Ministry of Petroleum and Natural Gas', 'Indian Oil Corporation Limited'],
    cpioDesignation: 'General Manager (Corporate Communications & RTI)',
    officeAddress: 'IndianOil Bhavan, 9, Ali Yavar Jung Marg, Bandra (East), Mumbai - 400051',
    pincode: '400051',
    stateLgdCode: 27, // Maharashtra
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'Executive Director (HR) & FAA',
    complianceRating: 94,
    medianResponseDays: 19,
  },
  {
    id: 'pa-up-revenue-005',
    ministryId: 'min-up-gov',
    ministryName: 'Government of Uttar Pradesh',
    canonicalName: 'Tehsil Office Ballia (Revenue & Land Records)',
    hindiName: 'तहसील कार्यालय बलिया (राजस्व एवं चकबंदी)',
    portalType: 'OFFLINE_SPEED_POST',
    dropdownPath: ['Uttar Pradesh Revenue Council', 'Collectorate Ballia', 'Tehsil Ballia Sadar'],
    cpioDesignation: 'Sub-Divisional Magistrate (SDM) / Tehsildar & SPIO',
    officeAddress: 'Tehsil Parisar, Collectorate Compound, Ballia, Uttar Pradesh - 277001',
    pincode: '277001',
    stateLgdCode: 9, // UP
    districtLgdCode: 172,
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'District Magistrate & First Appellate Authority, Ballia',
    complianceRating: 46,
    medianResponseDays: 42,
  },
  {
    id: 'pa-delhi-pwd-006',
    ministryId: 'min-gnctd',
    ministryName: 'Government of NCT of Delhi',
    canonicalName: 'Public Works Department (PWD Delhi) - Flyover Project Div',
    hindiName: 'लोक निर्माण विभाग (दिल्ली)',
    portalType: 'STATE_ONLINE',
    portalId: 'PWD_DELHI',
    dropdownPath: ['Government of NCT of Delhi', 'Public Works Department', 'Roads & Bridges Division'],
    cpioDesignation: 'Executive Engineer (Flyover Division II) & PIO',
    officeAddress: '12th Floor, MSO Building, I.P. Estate, New Delhi - 110002',
    pincode: '110002',
    stateLgdCode: 7,
    isSec24Exempt: false,
    appellateAuthorityDesignation: 'Superintending Engineer (Civil) & FAA',
    complianceRating: 64,
    medianResponseDays: 31,
  }
];

export const INITIAL_DOSSIERS: ICitizenRTIDossier[] = [
  {
    dossierId: 'dossier-nhai-001',
    citizenUuid: 'citizen-priya-law-01',
    title: 'NH-44 Toll Road Bitumen Quality & Measurement Book Audit',
    targetAuthority: INITIAL_PUBLIC_AUTHORITIES[0],
    filingChannel: 'CENTRAL_ONLINE',
    govRegistrationNumber: 'MORTH/R/2026/00192',
    rawGrievanceNarrative: 'Why was the newly constructed flyover on NH-44 damaged in 3 months? Who approved the asphalt density tests?',
    categoryKey: 'ROAD_POTHOLE',
    queryBlocks: [
      {
        id: 'qb-101',
        pointNumber: 1,
        recordType: 'WORK_MEASUREMENT_BOOK',
        certifiedQueryText: '1. Certified copy of the Work Measurement Book (MB) No. 441/B for KM 120-145 patch overlay executed by EPC Contractor.',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(d)', '10'],
      },
      {
        id: 'qb-102',
        pointNumber: 2,
        recordType: 'TENDER_BID_CHART',
        certifiedQueryText: '2. Certified copy of the comparative financial bid evaluation statement and quality testing certificates for asphalt bitumen density under Tender Ref: NHAI-440.',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(d)'],
      },
      {
        id: 'qb-103',
        pointNumber: 3,
        recordType: 'CITIZEN_CHARTER',
        certifiedQueryText: '3. Certified copy of the Citizen Charter specifying defect liability warranty clause and penalty deductions made from contractor bank guarantee.',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(j)'],
      }
    ],
    totalCharacterCount: 1420,
    isWordBudgetCompliant: true,
    maskedAadhaar: 'XXXX-XXXX-8821',
    proxyAddressUsed: 'Chamber 402, High Court Bar Association, Sher Shah Road, New Delhi',
    merkleRootHash: 'a49f82c091ba38e12480bf1390aa76210f9483dc47120a4b6910e583091ab772',
    statutoryClock: {
      filedDate: '2026-09-14T10:24:00+05:30',
      deliveryConfirmedDate: '2026-09-17T11:00:00+05:30',
      currentStatutoryDeadline: '2026-10-17T17:00:00+05:30',
      daysRemaining: 15,
      totalDays: 30,
      stage: 'PENDING_CPIO',
      isOverdue: false,
      hopCount: 0,
      sec7_6_FeeWaiverActive: false,
    },
    createdAt: '2026-09-14T10:24:00+05:30',
    updatedAt: '2026-09-17T11:00:00+05:30',
  },
  {
    dossierId: 'dossier-epfo-002',
    citizenUuid: 'citizen-arvind-act-02',
    title: 'EPFO Higher Pension Sanction & File Noting Transparency',
    targetAuthority: INITIAL_PUBLIC_AUTHORITIES[1],
    filingChannel: 'CENTRAL_ONLINE',
    govRegistrationNumber: 'EPFOG/R/2026/04910',
    rawGrievanceNarrative: 'My pension revision under Supreme Court order has been pending for 9 months with no intimation from regional office.',
    categoryKey: 'PENSION_DELAY',
    queryBlocks: [
      {
        id: 'qb-201',
        pointNumber: 1,
        recordType: 'FILE_NOTING',
        certifiedQueryText: '1. Certified copy of the calculation sheet, internal audit notings, and clearance checklist for PPO Revision Dossier Ref: DL/CPM/49102.',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(j)'],
      },
      {
        id: 'qb-202',
        pointNumber: 2,
        recordType: 'ORDER_COPY',
        certifiedQueryText: '2. Certified copy of the administrative instructions issued to Field Offices regarding statutory compliance of Apex Court directions in SC CA No. 8143-8144/2022.',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(d)'],
      }
    ],
    totalCharacterCount: 980,
    isWordBudgetCompliant: true,
    maskedAadhaar: 'XXXX-XXXX-4109',
    proxyAddressUsed: 'Post Box No. 812, Parliament Street HPO, New Delhi - 110001',
    merkleRootHash: 'c718b29304e8d891b29402847ff1990234a919203847581938b819284758b910',
    statutoryClock: {
      filedDate: '2026-08-28T09:15:00+05:30',
      deliveryConfirmedDate: '2026-08-30T10:00:00+05:30',
      currentStatutoryDeadline: '2026-09-29T17:00:00+05:30',
      daysRemaining: 0,
      totalDays: 30,
      stage: 'DEEMED_REFUSAL',
      isOverdue: true,
      hopCount: 0,
      sec7_6_FeeWaiverActive: true,
    },
    createdAt: '2026-08-28T09:15:00+05:30',
    updatedAt: '2026-09-30T10:00:00+05:30',
  },
  {
    dossierId: 'dossier-ballia-003',
    citizenUuid: 'citizen-ramesh-rural-03',
    title: 'Ballia Gram Panchayat Ration Card Blockage & Physical Muster Roll',
    targetAuthority: INITIAL_PUBLIC_AUTHORITIES[4],
    filingChannel: 'OFFLINE_SPEED_POST',
    postalBarcode: 'EU918239102IN',
    rawGrievanceNarrative: 'राशन कार्ड 6 महीने से बंद कर दिया है, कोटेदार अनाज नहीं दे रहा और बोलता है ऊपर से नाम कट गया है।',
    categoryKey: 'RATION_DELAY',
    queryBlocks: [
      {
        id: 'qb-301',
        pointNumber: 1,
        recordType: 'FILE_NOTING',
        certifiedQueryText: '1. उचित दर विक्रेता दुकान संख्या 42 ग्राम पंचायत का विगत 6 माह (अप्रैल से सितम्बर 2026) का भौतिक वितरण स्टॉक रजिस्टर एवं ई-पॉस (e-PoS) मशीन सर्वर लॉग की प्रमाणित प्रति।',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(j)'],
      },
      {
        id: 'qb-302',
        pointNumber: 2,
        recordType: 'ORDER_COPY',
        certifiedQueryText: '2. राष्ट्रीय खाद्य सुरक्षा अधिनियम (NFSA 2013) के अंतर्गत राशन कार्ड निरस्तीकरण आदेश एवं क्षेत्रीय खाद्य आपूर्ति निरीक्षक (Supply Inspector) की जांच आख्या की प्रमाणित प्रति।',
        sec2fCompliant: true,
        preemptedClauses: ['8(1)(d)', '10'],
      }
    ],
    totalCharacterCount: 760,
    isWordBudgetCompliant: true,
    maskedAadhaar: 'XXXX-XXXX-9912',
    proxyAddressUsed: 'C/o Common Service Centre, Gram Panchayat Bhawan, Ballia - 277001',
    merkleRootHash: 'e819b93021948571829485718294857182948571829485718294857182948571',
    statutoryClock: {
      filedDate: '2026-09-20T14:30:00+05:30',
      deliveryConfirmedDate: '2026-09-24T12:00:00+05:30',
      currentStatutoryDeadline: '2026-10-24T17:00:00+05:30',
      daysRemaining: 22,
      totalDays: 30,
      stage: 'PENDING_CPIO',
      isOverdue: false,
      hopCount: 0,
      sec7_6_FeeWaiverActive: false,
    },
    createdAt: '2026-09-20T14:30:00+05:30',
    updatedAt: '2026-09-24T12:00:00+05:30',
  }
];

export const INITIAL_TIMELINE_EVENTS: Record<string, TimelineEvent[]> = {
  'dossier-nhai-001': [
    {
      id: 'te-1',
      type: 'APPLICATION_FILED',
      timestamp: '2026-09-14 10:24 AM',
      title: 'RTI Application Successfully Filed',
      description: 'Filed via NIC Central RTI Portal (rtionline.gov.in). Statutory fee ₹10 paid via SBI ePay gateway.',
      status: 'COMPLETED',
      referenceNo: 'MORTH/R/2026/00192',
    },
    {
      id: 'te-2',
      type: 'SPEED_POST_DELIVERED',
      timestamp: '2026-09-17 11:00 AM',
      title: 'Application Receipt Acknowledged by NHAI CPIO',
      description: 'Marked to Chief General Manager (Tech-II) & CPIO. 30-day statutory countdown initiated under Section 7(1).',
      status: 'COMPLETED',
    },
    {
      id: 'te-3',
      type: 'SEC6_3_TRANSFERRED',
      timestamp: '2026-09-22 03:45 PM',
      title: 'Section 6(3) Transfer Hop (+5 Days Added)',
      description: 'Partially transferred to Regional Project Director, NHAI PIU Varanasi. +5 Statutory days automatically calibrated by Neptune SLA engine.',
      status: 'COMPLETED',
      statutoryDaysAdded: 5,
    },
    {
      id: 'te-4',
      type: 'CPIO_REPLY_RECEIVED',
      timestamp: 'Pending CPIO Desk',
      title: 'Statutory 30-Day Reply Window',
      description: '15 days remaining before Section 7(6) Deemed Refusal triggers.',
      status: 'ACTIVE',
    }
  ],
  'dossier-epfo-002': [
    {
      id: 'te-21',
      type: 'APPLICATION_FILED',
      timestamp: '2026-08-28 09:15 AM',
      title: 'RTI Application Submitted',
      description: 'Filing confirmed on Central Portal. Registration EPFOG/R/2026/04910 generated.',
      status: 'COMPLETED',
      referenceNo: 'EPFOG/R/2026/04910',
    },
    {
      id: 'te-22',
      type: 'SPEED_POST_DELIVERED',
      timestamp: '2026-08-30 10:00 AM',
      title: 'Delivered to Central PF Commissioner Desk',
      description: 'Statutory 30-day timer commenced.',
      status: 'COMPLETED',
    },
    {
      id: 'te-23',
      type: 'DEEMED_REFUSAL_TRIGGERED',
      timestamp: '2026-09-30 00:00 AM',
      title: 'Statutory SLA Breached: DEEMED REFUSAL',
      description: 'CPIO failed to furnish reply within 30 statutory days. Section 7(6) Fee Waiver is now permanently locked (All future records are 100% FREE). 1-Tap Section 19(1) First Appeal unlocked.',
      status: 'ACTIVE',
    }
  ]
};
